### ISSUE TITLE
Missing RTE configuration

### ISSUE THREAD

**Issue by liayn** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#328]
Crossposting from a report over here:
https://github.com/FriendsOfTYPO3/rtehtmlarea/issues/54#issuecomment-1254983691

Just to be sure we do not forget it

**Comment by bj0hn** [comment]
I had also described the problem here before:

https://forge.typo3.org/issues/98244#change-475774

The options are still available! 
If the better way now is to write this in a yaml file this should be documented best with examples. 

I don't know how the yaml syntax looks like.

**Comment by brotkrueml** [comment]
These should be placed in the docs for EXT:rte_ckeditor: https://docs.typo3.org/c/typo3/cms-rte-ckeditor/11.5/en-us/Configuration/Index.html

We are happy, if someone could provide a PR for this (who is also in this topic).

**Comment by DavidBruchmann** [comment]
As the crossposting is closed I think this can be closed too.

**Comment by bj0hn** [comment]
I don't think this is solved.

I still can't find anything about it in the documentation.

I just tested it with TYPO3 12.2 these configuration options are still available!!!!

```
RTE {
    default {
        buttons.link {
            options.removeItems = page, folder, file, url, email
        }
  }
}
```

Result:

![grafik](https://user-images.githubusercontent.com/42844433/222120170-256f0a55-8391-4302-bee4-19e3c98c8810.png)


Before:

![grafik](https://user-images.githubusercontent.com/42844433/222122196-bb146185-d49a-4411-a3df-41a669a0e49d.png)


BUT the documentation is lost to this. 

Also, I can't find any documentation on setting the link defaults. It used to work like this:

```
RTE {
	default {
		classesAnchor {
			page {
				class = my-link-class
				type = page
				titleText = 
				target =
			}
        }
    }
}
```

**Comment by DavidBruchmann** [comment]
I think this pages should help with it's linked items:  
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Rte/RteCkeditorSysext.html

**Comment by liayn** [comment]
@DavidBruchmann Last time I checked, this was indeed missing!
The cross-post was closed, because it was rather a transfer to here

**Comment by DavidBruchmann** [comment]
Ohh I see about the crossposting.
I hope the linked info is helping enough, for distinct issues that might be missing feel free to add some questions here, it's read even it's closed.

**Comment by bj0hn** [comment]
No, the link does not help. Particular configuration options from the old HTMLarea documentation are missing. In my opinion, some of the HTMLarea passages have to go here:

https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/PageTsconfig/Rte.html

e.g. TSConfig:

`RTE.default.buttons.link.options.removeItems = page, folder, file, url, email`

I checked the above in TYPO3 12.2, it still works.



Meanwhile I found out that in yaml it must look like this:

`blindLinkOptions: "page, folder, file, url, email".`

But this seems to be lost in the documentation. The search in the documentation finds "blindLinkOptions" only for TYPO3 7 LTS.


Also these options for `classesAnchor` still work via the ckeditor yaml file:

https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/main/en-us/Configuration/PageTsconfig/classesAnchor/Index.html#classesanchor

But I can't find anything about it in the whole documentation. The search returns results only in the old obsolete HTMLarea documentation for `classesAnchor `.

**Comment by DavidBruchmann** [comment]
@bj0hn  Ok, thanks for doing the tests!
Would you like to write the corresponding chapter(s) perhaps?
It can be copy and paste from old documentation of course.

**Comment by DavidBruchmann** [comment]
In TSConfig this page has to be changed:  
https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/PageTsconfig/Rte.html

Here could be something changed:
https://docs.typo3.org/c/typo3/cms-rte-ckeditor/11.5/en-us/Configuration/ConfigureTypo3.html
https://docs.typo3.org/c/typo3/cms-rte-ckeditor/11.5/en-us/Configuration/Concepts.html

**Comment by bj0hn** [comment]
@DavidBruchmann All right, I'll give it a try :)

**Comment by DavidBruchmann** [comment]
@bj0hn that's great! thanks!

**Comment by bj0hn** [comment]
@DavidBruchmann For the `button.link` properties I created a merge request. I hope this fits.

But for the `classesAnchor `properties I don't know what to do. If I install TYPO3 12.2. via composer there is the file 
`\typo3\cms-rte-ckeditor\Configuration\RTE\Default.yaml`

At the very end of the file I find the properties I am looking for ( `#Button config and default`)

If I then look into the repro of rte_ckeditor I don't find these properties. 

https://github.com/TYPO3-CMS/rte_ckeditor/blob/main/Configuration/RTE/Default.yaml

May be wrong repro?

More importantly, I can't find anything about this in the documentation either. 

The following TYPO3 specific properties would need to be documented  (taken from a fresh TYPO3 12.2 installation)

```
[...]

#Button config and defaults
buttons:
    link:
        relAttribute:
            enabled: true
        targetSelector:
            disabled: false
        properties:
            class:
                allowedClasses: 'link-internal,link-internal-blank,link-download,link-external,link-external-blank,link-mail'
        page:
            properties:
                class:
                    default: 'link-internal'
        file:
            properties:
                class:
                    default: 'link-download'
        url:
            properties:
                class:
                    default: 'link-external-blank'
                #rel:
                #    default: 'external noopener noreferrer'
        mail:
            properties:
                class:
                    default: 'link-mail'

# Classes config
classesAnchor:
    linkInternal:
        class: 'link-internal'
        type: 'page'
    linkInternalBlank:
        class: 'link-internal-blank'
        type: 'page'
        target: '_blank'
    linkDownload:
        class: 'link-download'
        type: 'file'
    linkExternal:
        class: 'link-external'
        type: 'url'
        #rel: 'external noopener noreferrer'
    linkExternalBlank:
        class: 'link-external-blank'
        type: 'url'
        target: '_blank'
        #rel: 'external noopener noreferrer'
    linkMail:
        class: 'link-mail'
        type: 'mail'
        
blindLinkOptions: "folder,file"


```
